### ISSUE TITLE
TypeError getLoggable is not a function

### ISSUE THREAD

**Issue by pacoyang** [huan/state-switch#50]
`brolog ^1.13.6` not exist function `getLoggable`, throw error:
TypeError: (0 , brolog_1.getLoggable) is not a function
https://github.com/huan/state-switch/blob/main/src/state-switch.ts#L12

**Comment by huan** [comment]
Please upgrade `brolog@1.14`+, or wait for the updated `state-switch@1.6.3`+ to fix this dependency problem.

**Comment by pacoyang** [comment]
I'm having this error with the latest version of `wechaty-puppet-wechat` which depends on `state-switch@1.6.1`.

**Comment by huan** [comment]
Would you like to help us by sending a PR to upgrade the `state-switch` dependency version to 1.6.3 in the `wechaty-puppet-wechat` package.json?

I believe the problem can be fixed after this upgrade.

**Comment by pacoyang** [comment]
Here is the PR https://github.com/wechaty/puppet-wechat/pull/188
I have found my mistake that the `brolog` version is still 1.12.4 in node_modules caused this error. After removing the `yarn.lock` and reinstalling again, I fix this problem.

**Comment by huan** [comment]
Great to know that you have solved your problem, cheers!
