### ISSUE TITLE
TypeError: state_switch_1.BooleanIndicator is not a constructor

### ISSUE THREAD

**Issue by WhiteWatson** [huan/state-switch#51]
使用electron打包WeChaty项目后出现
`TypeError: state_switch_1.BooleanIndicator is not a constructor`
electron开发环境没有任何问题

node version v14.16.1
electron version v13.3.0
wechaty version 1.20.2

**Comment by huan** [comment]
Can you provide more details, like reproducible steps?

**Comment by WhiteWatson** [comment]
我的state-switch 版本没有更新到1.7.1，缺少BooleanIndicator的export，使用 resolutions 更新包到1.7.1解决了
